@echo off

set HOMETEL=
set SYSTELCFG=
set USETELCFG=

if defined _OLD_VIRTUAL_PYTHONHOME (
    set "PYTHONHOME=%_OLD_VIRTUAL_PYTHONHOME%"
    set _OLD_VIRTUAL_PYTHONHOME=
)

if defined _OLD_VIRTUAL_PATH (
    set "PATH=%_OLD_VIRTUAL_PATH%"
)

if defined _OLD_VIRTUAL_PYTHONUNBUFFERED (
    set "PYTHONUNBUFFERED=%_OLD_VIRTUAL_PYTHONUNBUFFERED%"
)
