{% set name = "telemac-mascaret" %}
{% set version = "v8p4r0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: telemac-mascaret
    sha256: cfa2c05e41b28ba8aaea19b4b483e6d848bb08f823c8526c0824953a1cb4d564
  - path: ../src

build:
  number: 1
  script_env:
    - TELEMAC_VERSION={{ version }}

requirements:
  build:
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-metis
    - m2w64-msmpi
    - m2w64-mumps
    - m2w64-scalapack
    - m2w64-toolchain
    - matplotlib
    - numpy <1.22.0
    - python <3.11
    - scipy <1.11
  run:
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-metis
    - m2w64-msmpi
    - m2w64-mumps
    - m2w64-scalapack
    - m2w64-toolchain
    - matplotlib
    - mpi4py
    - numpy <1.22.0
    - python <3.11
    - scipy <1.11

test:
  files:
    - tests/*  # [win]
  requires:
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-metis
    - m2w64-msmpi
    - m2w64-mumps
    - m2w64-scalapack
    - m2w64-toolchain
    - matplotlib
    - mpi4py
    - numpy <1.22.0
    - python <3.11
    - scipy <1.11
  commands:
    - python -m config
    - telemac-debug on
    - python -m config
    # - cd tests/malpasset
    # - python -m telemac2d --ncsize=8 t2d_malpasset-fine.cas


about:
  home: http://www.opentelemac.org/
  license: GPLv3
  summary: Telemac-Mascaret
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/
  dev_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/

extra:
  recipe-maintainers:
    - nicogodet
