{% set name = "opentelemac" %}
{% set version = "v8p4r1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: opentelemac
    sha256: b48a0ee5cb43a68bc7255357544810ea67ea918a5ffd7fd61eeed41be4cf7b71

build:
  {% set build_pin = mpi_prefix + '_*' %}
  number: {{ build }}
  script_env:
    - TELEMAC_VERSION={{ version }}
  skip_compile_pyc:
    - "*/examples/*"
    - "*/notebooks/*"

outputs: 
  - name: {{ name }}-examples
    build:
      script: "%RECIPE_DIR%/build-examples.bat" # [win]
      script: "$RECIPE_DIR/build-examples.sh"   # [not win]

  - name: {{ name }}-documentation
    build:
      script: "%RECIPE_DIR%/build-documentation.bat" # [win]
      script: "$RECIPE_DIR/build-documentation.sh"   # [not win]
  
  - name: {{ name }}
    requirements:
      host:
        # Windows
        - m2-sed                    # [win]
        - m2w64-metis               # [win]
        - m2w64-toolchain           # [win]
        - m2w64-dlfcn               # [win]
        - m2w64-msmpi               # [win]
        - mumps-otm                 # [win]
        - scalapack-otm             # [win]
        # Linux / MacOS
        - {{ compiler('fortran') }} # [not win]
        - openmpi                   # [not win]
        - openmpi-mpifort           # [not win]
        - {{ compiler('gcc') }}     # [not win]
        - {{ compiler('gxx') }}     # [not win]
        - binutils                  # [not win]
        - hdf5 <1.11                # [not win]
        - metis                     # [not win]
        - libmed                    # [not win]
        - mumps-mpi                 # [not win]
        - scalapack                 # [not win]
        - parmetis                  # [not win]
        - gotm-otm                  # [not win]
        # Vendors
        - med-otm
        - aed2-otm
        # Python
        - matplotlib
        - numpy <1.22.0
        - python <3.11
        - scipy <1.11
      run:
        # Windows
        - m2-sed                    # [win]
        - m2w64-metis               # [win]
        - m2w64-toolchain           # [win]
        - m2w64-dlfcn               # [win]
        - m2w64-msmpi               # [win]
        - mumps-otm                 # [win]
        - scalapack-otm             # [win]
        # Linux / MacOS
        - {{ compiler('fortran') }} # [not win]
        - openmpi                   # [not win]
        - openmpi-mpifort           # [not win]
        - {{ compiler('gcc') }}     # [not win]
        - {{ compiler('gxx') }}     # [not win]
        - binutils                  # [not win]
        - hdf5 <1.11                # [not win]
        - metis                     # [not win]
        - libmed                    # [not win]
        - mumps-mpi                 # [not win]
        - scalapack                 # [not win]
        - parmetis                  # [not win]
        - gotm-otm                  # [not win]
        # Vendors
        - med-otm
        - aed2-otm
        # Python
        - matplotlib
        - mpi4py
        - numpy <1.22.0
        - python <3.11
        - scipy <1.11
        - jupyterlab
        - ipympl
        - ipykernel
    # test:
    #   script: run_test.bat

about:
  home: http://www.opentelemac.org/
  license: GPLv3
  summary: openTelemac
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/
  dev_url: https://github.com/nicogodet/telemac-mascaret-feedstock

extra:
  recipe-maintainers:
    - nicogodet
    - brey
    - tomsail
