{% set name = "telemac-mascaret" %}
{% set version = "v8p4r0" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: telemac-mascaret
    sha256: cfa2c05e41b28ba8aaea19b4b483e6d848bb08f823c8526c0824953a1cb4d564
  - path: ../src

build:
  number: {{ build }}
  script_env:
    - TELEMAC_VERSION={{ version }}
  skip_compile_pyc:
    - "*/examples/*"
    - "*/notebooks/*"

outputs: 
  - name: {{ name }}-examples
    build:
      script: "%RECIPE_DIR%/build-examples.bat"

  - name: {{ name }}-documentation
    build:
      script: "%RECIPE_DIR%/build-documentation.bat"
  
  - name: {{ name }}
    build:
      script: "%RECIPE_DIR%/build-telemac.bat"
    requirements:
      build:
        - m2-base
        - m2w64-metis
        - m2w64-msmpi
        - mumps-otm =5.2.1
        - scalapack-otm
        - hdf5-otm
        - med-otm
        - aed2-otm
        - m2w64-toolchain
        - m2w64-dlfcn
        - matplotlib
        - numpy <1.22.0
        - python <3.11
        - scipy <1.11
      run:
        - m2w64-metis
        - m2w64-msmpi
        - mumps-otm =5.2.1
        - scalapack-otm
        - hdf5-otm
        - med-otm
        - aed2-otm
        - m2w64-toolchain
        - m2w64-dlfcn
        - matplotlib
        - numpy <1.22.0
        - python <3.11
        - scipy <1.11
    # test:
    #   script: run_test.bat

about:
  home: http://www.opentelemac.org/
  license: GPLv3
  summary: Telemac-Mascaret
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/
  dev_url: https://github.com/nicogodet/telemac-mascaret-feedstock

extra:
  recipe-maintainers:
    - nicogodet
