{% set name = "opentelemac" %}
{% set version = "v8p4r1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: opentelemac
    sha256: b48a0ee5cb43a68bc7255357544810ea67ea918a5ffd7fd61eeed41be4cf7b71

build:
  {% set build_pin = mpi_prefix + '_*' %}
  number: {{ build }}
  script_env:
    - TELEMAC_VERSION={{ version }}


requirements:
  build:
    # Windows
    - m2-sed                    # [win]
    - m2w64-metis               # [win]
    - m2w64-toolchain           # [win]
    - m2w64-dlfcn               # [win]
    - msmpi-otm                 # [win]
    - mumps-otm                 # [win]
    - scalapack-otm             # [win]
    - med-otm                   # [win]
    - aed2-otm                  # [win]
    # - gotm-otm                  # [win]
    # Linux / MacOS
    - {{ compiler('fortran') }} # [not win]
    - openmpi                   # [not win]
    - openmpi-mpifort           # [not win]
    - {{ compiler('gcc') }}     # [not win]
    - {{ compiler('gxx') }}     # [not win]
    - binutils                  # [not win]
    - hdf5 <1.11                # [not win]
    - metis                     # [not win]
    - libmed                    # [not win]
    - mumps-mpi                 # [not win]
    - scalapack                 # [not win]
    - parmetis                  # [not win]
    - gotm-otm                  # [not win]
    # Python
    - numpy
    - python
    - scipy
  run:
    # Windows
    - m2-sed                    # [win]
    - m2w64-metis               # [win]
    - m2w64-toolchain           # [win]
    - msmpi-otm                 # [win]
    - mumps-otm                 # [win]
    - scalapack-otm             # [win]
    - med-otm                   # [win]
    - aed2-otm                  # [win]
    # - gotm-otm                  # [win]
    # Linux / MacOS
    - {{ compiler('fortran') }} # [not win]
    - openmpi                   # [not win]
    - openmpi-mpifort           # [not win]
    - {{ compiler('gcc') }}     # [not win]
    - {{ compiler('gxx') }}     # [not win]
    - binutils                  # [not win]
    - hdf5 <1.11                # [not win]
    - metis                     # [not win]
    - libmed                    # [not win]
    - mumps-mpi                 # [not win]
    - scalapack                 # [not win]
    - parmetis                  # [not win]
    - gotm-otm                  # [not win]
    # Python
    - matplotlib-base
    - numpy
    - python
    - scipy
  

about:
  home: http://www.opentelemac.org/
  license: GPLv3
  summary: openTelemac
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/
  dev_url: https://github.com/nicogodet/telemac-mascaret-feedstock

extra:
  recipe-maintainers:
    - nicogodet
    - brey
    - tomsail
